apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: pg-operator
  name: pg-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pg-operator
  template:
    metadata:
      labels:
        run: pg-operator
    spec:
      containers:
      - name: kubedb-pg
        image: kubedb/pg-operator:0.8.0-beta.0
        args:
        - run
        - --v=4
