apiVersion: v1
kind: Service
metadata:
  name: governing-postgres
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgres.k8sdb.com/name: postgres-demo
