apiVersion: v1
kind: Service
metadata:
  name: postgres-demo
  namespace: default
spec:
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgres.k8sdb.com/name: postgres-demo
