apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: api
  selector:
    app: postgres
    kubedb.com/role: primary
  type: NodePort
