apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres-1
  labels:
    app: postgres
spec:
  serviceName: "kubedb"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: aerokite/postgres:9.6.5-31
        ports:
        - containerPort: 5432
          name: api
        env:
        - name: "ARCHIVE_MODE"
          value: "on"
        - name: "PRIMARY_HOST"
          value: "postgres"
