apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "kubedb"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: aerokite/postgres:9.6.5-40
        ports:
        - containerPort: 5432
          name: api
        env:
        - name: "STANDBY"
          value: "hot"
        - name: "STREAMING"
          value: "synchronous"
        - name: "PRIMARY_HOST"
          value: "postgres-primary"
